FROM python:3.13-slim

WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy poetry files
COPY pyproject.toml poetry.lock ./

# Configure poetry to not create a virtual environment inside the container
RUN poetry config virtualenvs.create false

# Install dependencies
RUN poetry install --no-root

# Copy application code
COPY src/ ./src/
COPY model/ ./model/
# Expose the port
EXPOSE 8501

# Command to run Streamlit
CMD ["poetry", "run", "streamlit", "run", "src/streamlit_app.py"]